- name: Install Nginx and Set Up Monitoring for System Usage
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Install msmtp
      ansible.builtin.yum:
        name: msmtp
        state: present

    - name: Configure msmtp
      ansible.builtin.copy:
        dest: /etc/msmtprc
        content: |
          account default
          host smtp.gmail.com
          port 587
          auth on
          user jhansianthoti103@gmail.com
          password Jhansi@123
          tls on
          tls_starttls on
        mode: '0600'

    - name: Create log directory
      file:
        path: /var/log
        state: directory
        mode: '0755'

    - name: Copy the monitoring script to target nodes
      ansible.builtin.copy:
        src: monitor_usage.sh
        dest: /usr/local/bin/monitor_usage.sh
        mode: '0755'

    - name: Create the systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/monitor_usage.service
        content: |
          [Unit]
          Description=Monitor System Usage

          [Service]
          ExecStart=/usr/local/bin/monitor_usage.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd manager configuration
      ansible.builtin.command:
        cmd: systemctl daemon-reload

    - name: Enable the monitoring service to start on boot
      ansible.builtin.systemd:
        name: monitor_usage
        enabled: yes
        state: started

    - name: Start the monitoring service
      ansible.builtin.systemd:
        name: monitor_usage
        state: started
