- name: Install Nginx and Set Up Monitoring for System Usage
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Install ssmtp
      ansible.builtin.yum:
        name: ssmtp
        state: present

    - name: Configure ssmtp
      ansible.builtin.copy:
        dest: /etc/ssmtp/ssmtp.conf
        content: |
          root=jhansianthoti103@gmail.com
          mailhub=smtp.gmail.com:587
          AuthUser=jhansianthoti103@gmail.com
          AuthPass=Jhansi@123
          UseSTARTTLS=YES

    - name: Copy the monitoring script to target nodes
      ansible.builtin.copy:
        src: monitor_usage.sh
        dest: /usr/local/bin/monitor_usage.sh
        mode: '0755'

    - name: Create the systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/monitor_usage.service
        content: |
          [Unit]
          Description=Monitor System Usage

          [Service]
          ExecStart=/usr/local/bin/monitor_usage.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd manager configuration
      ansible.builtin.command:
        cmd: systemctl daemon-reload

    - name: Enable the monitoring service to start on boot
      ansible.builtin.systemd:
        name: monitor_usage
        enabled: yes
        state: started

    - name: Start the monitoring service
      ansible.builtin.systemd:
        name: monitor_usage
        state: started
