- name: Deploy Nginx and Monitor Resources
  hosts: all
  become: yes
  tasks:

    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Gather CPU usage
      ansible.builtin.shell: top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'
      register: cpu_usage
      changed_when: false

    - name: Gather RAM usage
      ansible.builtin.shell: free -m | awk 'NR==2{print $3}'
      register: ram_usage
      changed_when: false

    - name: Gather Disk usage
      ansible.builtin.shell: df -h | awk '$NF=="/" {print $5}'
      register: disk_usage
      changed_when: false

    - name: Create HTML report
      ansible.builtin.template:
        src: index.html.j2
        dest: index.html
      vars:
        cpu_usage_value: "{{ cpu_usage.stdout.strip() }}%"
        ram_usage_value: "{{ ram_usage.stdout.strip() }} MB"
        disk_usage_value: "{{ disk_usage.stdout.strip() }}"
