- name: Install and Configure Postfix, Nginx, and Monitoring
  hosts: all
  become: yes
  tasks:
    - name: Install Postfix, SASL authentication, mailx, and CA certificates
      ansible.builtin.yum:
        name:
          - postfix
          - cyrus-sasl-plain
          - ca-certificates
        state: present

    - name: Install mailx or mailutils
      ansible.builtin.yum:
        name: "{{ 'mailx' if ansible_distribution_major_version != '9' else 'mailutils' }}"
        state: present
      ignore_errors: yes
      register: mailx_install_result

    - name: Install mailutils if mailx installation failed
      ansible.builtin.yum:
        name: mailutils
        state: present
      when: mailx_install_result.failed

    - name: Verify Postfix installation
      ansible.builtin.command:
        cmd: rpm -q postfix
      register: postfix_check

    - name: Debug Postfix installation
      ansible.builtin.debug:
        msg: "{{ postfix_check.stdout }}"

    - name: Configure Postfix main.cf
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        line: "{{ item }}"
        create: yes
      loop:
        - relayhost = [smtp.gmail.com]:587
        - smtp_use_tls = yes
        - smtp_sasl_auth_enable = yes
        - smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
        - smtp_sasl_security_options = noanonymous
        - smtp_sasl_tls_security_options = noanonymous

    - name: Configure Postfix SASL credentials
      ansible.builtin.copy:
        dest: /etc/postfix/sasl_passwd
        content: |
          [smtp.gmail.com]:587 jhansianthoti103@gmail.com:yqlelzekdydtcccg
        mode: '0600'
        owner: root
        group: root

    - name: Create Postfix lookup table
      ansible.builtin.command:
        cmd: postmap /etc/postfix/sasl_passwd

    - name: Start and enable Postfix
      ansible.builtin.systemd:
        name: postfix
        state: started
        enabled: yes

    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Install msmtp and mailx
      ansible.builtin.yum:
        name: msmtp
        state: present

    - name: Configure msmtp
      ansible.builtin.copy:
        dest: /etc/msmtprc
        content: |
          account default
          host smtp.gmail.com
          port 587
          auth on
          user jhansianthoti103@gmail.com
          password yqlelzekdydtcccg
          tls on
          tls_starttls on
          tls_trust_file /etc/pki/tls/certs/ca-bundle.crt
        mode: '0600'
        owner: root
        group: root

    - name: Restart Postfix
      ansible.builtin.systemd:
        name: postfix
        state: restarted

    - name: Copy the monitoring script to target nodes
      ansible.builtin.copy:
        src: monitor_usage.sh
        dest: /usr/local/bin/monitor_usage.sh
        mode: '0755'

    - name: Create the systemd service file for the monitoring script
      ansible.builtin.copy:
        dest: /etc/systemd/system/monitor_usage.service
        content: |
          [Unit]
          Description=Monitor System Usage

          [Service]
          ExecStart=/usr/local/bin/monitor_usage.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd manager configuration
      ansible.builtin.command:
        cmd: systemctl daemon-reload

    - name: Enable the monitoring service to start on boot
      ansible.builtin.systemd:
        name: monitor_usage
        enabled: yes
        state: started

    - name: Start the monitoring service
      ansible.builtin.systemd:
        name: monitor_usage
        state: started

    - name: Test email sending
      ansible.builtin.command:
        cmd: echo "This is a test mail & Date $(date)" | msmtp jhansianthoti103@gmail.com
