- name: Deploy Nginx and monitor system resources
  hosts: all
  become: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Start Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Copy monitor_usage.sh to remote nodes
      ansible.builtin.copy:
        src: monitor_usage.sh
        dest: /usr/local/bin/monitor_usage.sh
        mode: '0755'

    - name: Execute monitor_usage.sh
      ansible.builtin.shell: 
        src: monitor_usage.sh


    - name: Update index.html with system information
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: Ensure index.html is readable
      ansible.builtin.file:
        path: /usr/share/nginx/html/index.html
        mode: '0644'
