- name: Install and verify Postfix
  hosts: all
  become: yes
  tasks:
    - name: Install Postfix and CA certificates
      ansible.builtin.yum:
        name:
          - postfix
          - ca-certificates
        state: present

    - name: Verify Postfix installation
      ansible.builtin.command:
        cmd: rpm -q postfix
      register: postfix_check

    - name: Debug Postfix installation
      ansible.builtin.debug:
        msg: "{{ postfix_check.stdout }}"
