---
- name: Install Nginx and Monitor System Resources
  hosts: all
  become: yes
  tasks:

    - name: Install Nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Nginx on RedHat/CentOS
      dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure Nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Gather CPU usage
      shell: top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'
      register: cpu_usage

    - name: Gather RAM usage
      shell: free -m | awk 'NR==2{print $3}'
      register: ram_usage

    - name: Gather Disk usage
      shell: df -h | awk '$NF=="/" {print $5}'
      register: disk_usage

    - name: Create HTML file with system information
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      vars:
        cpu_usage: "{{ cpu_usage.stdout }}%"
        ram_usage: "{{ ram_usage.stdout }} MB"
        disk_usage: "{{ disk_usage.stdout }}"

    - name: Restart Nginx to apply changes
      systemd:
        name: nginx
        state: restarted
